# -*- coding: utf-8 -*-
"""20221117.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E3d3SM89sHIIcuKjtaqfpPQ4kYZgfAIN
"""

'''
1.	Faça um programa que receba a temperatura média
de cada mês do ano e armazene-as em uma lista.
Após isto, calcule a média anual das temperaturas
e mostre todas as temperaturas acima da média anual,
e em que mês elas ocorreram
(mostrar o mês por extenso:
1 – Janeiro, 2 – Fevereiro, . . . ).
'''
# mes_media = [
#     ('janeiro', 25),
#     ('fevereiro', 25),
#     ('março', 25),
#     ('abril', 25),
#     ('maio', 25),
#     ('junho', 25),
#     ('julho', 25),
#     ('agosto', 25),
#     ('setembro', 50),
#     ('outubro', 25),
#     ('novembro', 25),
#     ('dezembro', 25),
# ]
 
# elementos = 0
# soma = 0
# for i in mes_media:
#   elementos = elementos + 1
#   soma = soma + i[1]

# media = soma/elementos

# for i in mes_media:
#   if i[1] > media:
#     print(f'o mes: {i[0]} teve a temperatura: {i[1]} \
# acima da média: {media:.2f}')

'''
2.	Utilizando listas faça um programa que faça
5 perguntas para uma pessoa sobre um crime.
As perguntas são:
a.	"Telefonou para a vítima?"
b.	"Esteve no local do crime?"
c.	"Mora perto da vítima?"
d.	"Devia para a vítima?"
e.	"Já trabalhou com a vítima?
 O programa deve no final emitir uma classificação
 sobre a participação da pessoa no crime.
 Se a pessoa responder positivamente a 2 questões
 ela deve ser classificada como "Suspeita",
 entre 3 e 4 como "Cúmplice" e 5 como "Assassino".
 Caso contrário, ele será classificado como "Inocente".
'''

# perguntas = [
#   "Telefonou para a vítima?",
#   "Esteve no local do crime?",
#   "Mora perto da vítima?",
#   "Devia para a vítima?",
#   "Já trabalhou com a vítima?",
# ]

# #respostas = []
# soma = 0
# print('responda 1 para sim e 0 para não')
# for pergunta in perguntas:
#   r = int(input(pergunta))
#   #respostas.append(r)
#   soma = soma + r

# if soma == 2:
#   print('suspeito')
# elif soma >= 3 and soma <= 4:
#   print('Cúmplice')
# elif soma == 5:
#   print('Assassino')
# else:
#   print('Inocente')

'''
3.	Faça um programa que leia um número indeterminado
de valores, correspondentes a notas, encerrando a
entrada de dados quando for informado um valor igual
a -1 (que não deve ser armazenado).
Após esta entrada de dados, faça:
a.	Mostre a quantidade de valores que foram lidos;
b.	Exiba todos os valores na ordem em que foram informados, um ao lado do outro;
c.	Exiba todos os valores na ordem inversa à que foram informados, um abaixo do outro;
d.	Calcule e mostre a soma dos valores;
e.	Calcule e mostre a média dos valores;
f.	Calcule e mostre a quantidade de valores acima da média calculada;
g.	Calcule e mostre a quantidade de valores abaixo de sete;
h.	Encerre o programa com uma mensagem;
'''
# numero = []
# while True:
#   n = int(input('entre com um numero: '))
#   if n == -1:
#     break
#   numero.append(n)

# print(numero)

numero = [2, 6, 9, 4]
n = len(numero)
print(n)
print(numero)
numero_inverso = []
soma = 0
for i in range(n):
  soma = soma + numero[i]
  numero_inverso.append(numero[n-1-i])
print(numero_inverso)
print(soma)
media = soma/n
print(media)

for i in numero:
  if i > media:
    print(f'numero: {i} acima media: {media}')
  elif i < media:
    print(f'numero: {i} abaixo media: {media}')

print('ola')