# -*- coding: utf-8 -*-
"""20221021.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZB4XI7CQVlT0IH04EoRRv_Z5Lj_J730H

# Exercícios Com Listas (vetor)
"""

'''
    1. Faça um Programa que leia um vetor
    de 5 números inteiros e mostre-os.
'''
# vetor =[]
# while True:
#   numero = int(input('Entre com um número: '))
#   if numero == -1:
#     break
#   vetor.append(numero)

# print(vetor)
# vetor = []
# elementos = int(input("quantos elementos? "))
# for i in range(elementos):
#   numero = int(input('Entre com um número: '))
#   vetor.append(numero)

vetor = [18, 24, 32, 45, 58]
for v in range(len(vetor)):
  print(v, ' - ', vetor[v])

vetor = [18, 24, 32, 45, 58]
for v in vetor:
  print(v)

'''
    2. Faça um Programa que leia um vetor
    de 10 números reais e mostre-os na
    ordem inversa.
'''
vetor = [18, 24, 32, 45, 58]
n = len(vetor)
# for v in range(n):
#   print(v, n-1-v)
#   #print(vetor[v])

# print()
for v in range(n):
  #print(v, n-1-v)
  print(vetor[n-1-v])

'''
    3. Faça um Programa que leia 4 notas,
    mostre as notas e a média na tela.
'''
vetor = [18, 24, 32, 45]
n = len(vetor)
soma = 0
# for v in range(n):
#   soma = soma + vetor[v]
for v in vetor:
  soma = soma + v

media = soma / n
print('As notas:', vetor)
print('media é: ', media)

'''
    4. Faça um Programa que leia um vetor de
    10 caracteres, e diga quantas
    consoantes foram lidas. Imprima as
    consoantes.
'''
vetor = ['c', 'b', 'a', 'd', 'e']
vogal = 0
consoante = 0
v_consoante = []
for v in vetor:
  #if v == 'a' or v == 'e' or v == 'i' or v == 'o' or v == 'u':
  if v in ('a', 'e', 'i', 'o', 'u'):
    vogal = vogal + 1
  else:
    consoante = consoante + 1
    v_consoante.append(v)

print('vogal:', vogal)
print('consoante:', consoante, v_consoante)

lst = []
lst.append(3)
lst.append('ugb')
lst.append(2.8)
lst.append(True)
lst.append([5,7])
lst.append((7,4))

for i in range(len(lst[1])):
  print(lst[1][i])
lst[1][1]

'''
    5. Faça um Programa que leia 20 números
    inteiros e armazene-os num vetor.
    Armazene os números pares no vetor
    PAR e os números IMPARES no vetor impar.
    Imprima os três vetores.
'''
# vetor =[]
# for i in range(5):
#   numero = int(input('Entre com um número: '))
#   vetor.append(numero)

vetor = [5, 6, 7, 8, 2]
par = []
impar = []
for v in vetor:
  if v % 2 == 0:
    par.append(v)
  else:
    impar.append(v)

print('vetor:', vetor)
print('par:', par)
print('impar:', impar)

'''
    6. Faça um Programa que peça as quatro notas
    de 10 alunos, calcule e armazene num vetor
    a média de cada aluno, imprima o número de
    alunos com média maior ou igual a 7.0.
'''

# registro = []
# for i in range(3):
#   aluno = input('entre com o aluno:')
#   notas = []
#   for j in range(4):
#     nota = float(input(f'Entre com a nota{j+1}:'))
#     notas.append(nota)
#   registro.append((aluno, notas))
# print(registro)

registros = [
 ('andre', [5.0, 7.0, 2.0, 9.0]),
 ('pedro', [3.0, 7.0, 2.0, 3.0]),
 ('joao', [10.0, 9.0, 8.0, 4.0])
]
media = []
for r in registros:
  print(r[1])
  soma = 0
  for j in r[1]:
    soma = soma + j
  media.append((r[0],soma/4))
  print('aluno:', r[0], ', soma:', soma)
  print(media)
  contador = 0
  for i in media:
    if i[1] >= 7:
      contador = contador + 1
  print('aprovados:',contador)

lst = ('andre', [5.0, 7.0, 2.0, 9.0])
s = 0
for i in lst[1]:
  s = s + i
s

'''
    7. Faça um Programa que leia um vetor
    de 5 números inteiros, mostre a soma,
    a multiplicação e os números.
'''
vetor = [3, 2, 5, 4, 1]
soma = 0
m = 1
for v in vetor:
  soma = soma + v
  m = m * v
print('soma:', soma)
print('multiplicação:', m)
print('os numeros:', vetor)

'''
    8. Faça um Programa que peça a idade
    e a altura de 5 pessoas, armazene cada
    informação no seu respectivo vetor.
    Imprima a idade e a altura na ordem
    inversa a ordem lida.
'''
# pessoas = []
# for p in range(5):
#   pessoa = input('entre com o nome:')
#   idade = int(input('entre com a idade:'))
#   altura = float(input('entre com a altura:'))
#   pessoas.append([pessoa, idade, altura])
# print(pessoas)

pessoas = [
    ['andre', 48, 1.8],
    ['joao', 25, 1.7],
    ['izar', 18, 1.68],
    ['kaua', 89, 2.1],
    ['carlos', 57, 1.95]
  ]

n = len(pessoas)
for v in range(n):
  print(pessoas[n-1-v][0], pessoas[n-1-v][2], pessoas[n-1-v][1])

'''
    9. Faça um Programa que leia um vetor A
    com 10 números inteiros, calcule e
    mostre a soma dos quadrados dos elementos
    do vetor.
'''
vetor = [5, 3, 2]
s = 0
for v in vetor:
  s = s + v**2
print('soma:', s)

'''
    10. Faça um Programa que leia dois
    vetores com 10 elementos cada.
    Gere um terceiro vetor de 20 elementos,
    cujos valores deverão ser compostos
    pelos elementos intercalados dos dois
    outros vetores.
'''
vetor_1 = [1, 3, 5, 7, 9]
vetor_2 = [2, 4, 6, 8, 10]
vetor_3 = []
for i in range(5):
  #print(vetor_1[i], ' - ' ,vetor_2[i])
  vetor_3.append(vetor_1[i])
  vetor_3.append(vetor_2[i])

print(vetor_3)